---
image: docker:stable

services:
  - docker:dind

variables:
  LINUX_IMAGE: $CI_REGISTRY_IMAGE/unit-test:$CI_COMMIT_REF_SLUG
  CCACHE_DIR: ccache

stages:
  - prepare
  - test

docker-linux:
    image: docker:stable
    stage: prepare
    before_script:
      - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    script:
      - docker build --pull -t $LINUX_IMAGE .
      - docker push $LINUX_IMAGE

.job-template: &job_definition
    stage: test
    image: $LINUX_IMAGE
    cache:
        paths:
          - extlibs/
          - ccache/
    before_script:
      - ccache -s
      - which gcc
      - cp -r /extlibs/ extlibs/
      - find extlibs/ -type f -name "*.zip"
    artifacts:
        paths:
          - '*.memcheck'
          - out/

unit-test:
    <<: *job_definition
    script:
      - python auto_build.py unit_tests

linux-secured:
    <<: *job_definition
    script:
      - python auto_build.py linux_secured

linux-unsecured:
    <<: *job_definition
    script:
      - python auto_build.py linux_unsecured

linux-secured-with-tcp:
    <<: *job_definition
    script:
      - python auto_build.py linux_secured_with_tcp

linux-unsecured-with-tcp:
    <<: *job_definition
    script:
      - python auto_build.py linux_unsecured_with_tcp
