---
image: docker:stable

services:
  - docker:dind

variables:
  - UNIT_TEST_IMAGE: $CI_REGISTRY/unit-test:$CI_COMMIT_REF_SLUG

stages:
  - prepare
  - test

docker unit-test:
    image: docker:stable
    stage:
      - prepare
    before_script:
      - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    script:
      - docker build --pull -t $UNIT_TEST_IMAGE .
      - docker push $UNIT_TEST_IMAGE

prep extlibs:
    stage:
      - prepare
    cache:
        paths:
          - extlibs/
    script:
      - git clone https://github.com/intel/tinycbor.git extlibs/tinycbor/tinycbor -b v0.5.1 
      - git clone https://github.com/dthaler/libcoap.git extlibs/libcoap/libcoap -b IoTivity-1.4
      - git clone https://github.com/ARMmbed/mbedtls.git extlibs/mbedtls/mbedtls -b mbedtls-2.4.2

unit-test:
    image: $UNIT_TEST_IMAGE
    stage:
      - test
    cache:
        paths:
          - extlibs/
        policy: pull
    script:
      - python auto_build.py unit_tests
