---
image: docker:stable

services:
  - docker:dind

variables:
  UNIT_TEST_IMAGE: $CI_REGISTRY_IMAGE/unit-test:$CI_COMMIT_REF_SLUG
  CCACHE_DIR: ccache

stages:
  - prepare
  - test

docker-unit-test:
    image: docker:stable
    stage: prepare
    before_script:
      - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    script:
      - docker build --pull -t $UNIT_TEST_IMAGE .
      - docker push $UNIT_TEST_IMAGE

prep-extlibs:
    image: buildpack-deps:scm
    stage: prepare
    cache:
        paths:
          - extlibs/
          - ccache/
    script:
      - git clone https://github.com/intel/tinycbor.git extlibs/tinycbor/tinycbor -b v0.5.1 
      - git clone https://github.com/dthaler/libcoap.git extlibs/libcoap/libcoap -b IoTivity-1.4
      - git clone https://github.com/ARMmbed/mbedtls.git extlibs/mbedtls/mbedtls -b mbedtls-2.4.2

unit-test:
    image: $UNIT_TEST_IMAGE
    stage: test
    cache:
        paths:
          - extlibs/
          - ccache/
    before_script:
      - which gcc
      # - cp ccache /usr/local/bin/
      # - ln -s ccache /usr/local/bin/gcc
      # - ln -s ccache /usr/local/bin/g++
      # - ln -s ccache /usr/local/bin/cc
      # - ln -s ccache /usr/local/bin/c++
      - ccache -s
    script:
      - python auto_build.py unit_tests
