---
image: docker:stable

services:
  - docker:dind

variables:
  LINUX_IMAGE: $CI_REGISTRY_IMAGE/unit-test:$CI_COMMIT_REF_SLUG
  CCACHE_BASEDIR: $CI_PROJECT_DIR
  CCACHE_DIR: $CI_PROJECT_DIR/ccache
  CCACHE_COMPILERCHECK: content
  CONCURRENCY: 3

stages:
  - build
  - test

cache:
    paths:
      - extlibs/
      - $CI_PROJECT_DIR/ccache/

docker-linux:
    image: docker:stable
    stage: build
    only:
      - schedules
    when: manual
    before_script:
      - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    script:
      - docker build --pull -t $LINUX_IMAGE .
      - docker push $LINUX_IMAGE

.job-template: &job_definition
    stage: test
    image: $LINUX_IMAGE
    except:
      - schedules
    before_script:
      - "export PATH=/usr/lib/ccache:$PATH"
      - ccache -s
      - which gcc
      - cp -r /extlibs/* extlibs/
      - find extlibs/ -type f -name "*.zip"
    artifacts:
        paths:
          - '*.memcheck'
          - out/

.unit-test:
    <<: *job_definition
    script:
      - scons -j $CONCURRENCY TEST=1 VERBOSE=true RELEASE=false TARGET_TRANSPORT='IP' SECURED=True VALGRIND_CHECKS=False

linux-secured:
    <<: *job_definition
    script:
      - scons -j $CONCURRENCY VERBOSE=true RELEASE=false ERROR_ON_WARN=1

linux-secured-release:
    <<: *job_definition
    script:
      - scons -j $CONCURRENCY VERBOSE=true RELEASE=true ERROR_ON_WARN=1

linux-unsecured:
    <<: *job_definition
    script:
      - scons -j $CONCURRENCY VERBOSE=true RELEASE=false ERROR_ON_WARN=1 SECURED=0

linux-unsecured-release:
    <<: *job_definition
    script:
      - scons -j $CONCURRENCY VERBOSE=true RELEASE=true ERROR_ON_WARN=1 SECURED=0

.linux-secured-with-tcp:
    <<: *job_definition
    script:
      - scons -j $CONCURRENCY VERBOSE=true RELEASE=true ERROR_ON_WARN=1 WITH_TCP=1 WITH_CLOUD=1

.linux-unsecured-with-tcp:
    <<: *job_definition
    script:
      - scons -j $CONCURRENCY VERBOSE=true RELEASE=true ERROR_ON_WARN=1 WITH_TCP=1 TARGET_TRANSPORT='IP' SECURED=0
