---
image: docker:stable

services:
  - docker:dind

variables:
  LINUX_IMAGE: $CI_REGISTRY_IMAGE/unit-test:$CI_COMMIT_REF_SLUG
  CCACHE_DIR: ccache
  CCACHE_COMPILERCHECK: content

stages:
  - build
  - test

docker-linux:
    image: docker:stable
    stage: build
    only:
      - schedules
    when: manual
    before_script:
      - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    script:
      - docker build --pull -t $LINUX_IMAGE .
      - docker push $LINUX_IMAGE

.job-template: &job_definition
    stage: test
    image: $LINUX_IMAGE
    except:
      - schedules
    cache:
        paths:
          - extlibs/
          - ccache/
    before_script:
      - "export PATH=/usr/lib/ccache:$PATH"
      - ccache -s
      - which gcc
      - echo $PATH
      - cp -r /extlibs/* extlibs/
      - find extlibs/ -type f -name "*.zip"
    artifacts:
        paths:
          - '*.memcheck'
          - out/

.unit-test:
    <<: *job_definition
    script:
      - scons TEST=1 VERBOSE=true RELEASE=false TARGET_TRANSPORT='IP' SECURED=True VALGRIND_CHECKS=False

linux-secured:
    <<: *job_definition
    script:
      - scons VERBOSE=true RELEASE=true ERROR_ON_WARN=1

linux-unsecured:
    <<: *job_definition
    script:
      - scons VERBOSE=true RELEASE=true ERROR_ON_WARN=1 SECURED=0

.linux-secured-with-tcp:
    <<: *job_definition
    script:
      - scons VERBOSE=true RELEASE=true ERROR_ON_WARN=1 WITH_TCP=1 WITH_CLOUD=1

.linux-unsecured-with-tcp:
    <<: *job_definition
    script:
      - scons VERBOSE=true RELEASE=true ERROR_ON_WARN=1 WITH_TCP=1 TARGET_TRANSPORT='IP' SECURED=0
